### ISSUE TITLE
Create VCH fails in RC6 with "static in body should match..."

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#286] opened 2018-01-04 05:59 UTC
VIC RC6 :  vic-v1.3.0-rc6-3010-f8cc7317.ova

![image](https://user-images.githubusercontent.com/25006749/34551643-e0acea8e-f141-11e7-8a1e-544748c3b263.png)

Basic creation of VCH through UI with static IP address failed.

@jooskim @mdubya66

**Comment by AngieCris** [comment] 2018-01-04 06:13
@lgayatri What network field did you supply static IP address for? Also can you provide the request payload and the generated CLI commands?
(The request payload is in the inspect network tab. Let me know if you're not able to get it)

**Comment by lgayatri** [comment] 2018-01-04 06:17
Command generated:

./vic-machine-linux create --name virtual-container-host --compute-resource /Datacenter/host/Cluster/w2-hs2-d2612.eng.vmware.com --image-store CPBU_2TB_01 --base-image-size 8GB --bridge-network vxw-dvs-3444-virtualwire-1-sid-5000-VCH-LS-1 --bridge-network-range 172.16.0.0/12 --public-network DPortGroup --public-network-ip 10.197.37.192 --public-network-gateway 10.197.37.253 --dns-server 10.142.7.21 --tls-cname virtual-container-host --organization virtual-container-host --certificate-key-size 2048 --no-tlsverify --user Administrator@VSPHERE.LOCAL --thumbprint C1:6D:3E:41:A5:89:5E:89:FB:DB:82:2F:32:82:8E:54:53:8B:65:34 --target wdc-stvc3944-146-dhcp15.eng.vmware.com/Datacenter --ops-user Administrator@vsphere.local

The same when executed from CLI failed with
```
INFO[0000] ### Installing VCH ####
INFO[0000] vSphere password for Administrator@VSPHERE.LOCAL:
INFO[0003] vSphere password for Administrator@vsphere.local:
ERRO[0006] --------------------
ERRO[0006] vic-machine-linux create failed: Failed to parse the provided public network IP address 10.197.37.192: invalid CIDR address: 10.197.37.192

```
Filed #287 for the above issue.
@jak-atx

**Comment by lgayatri** [comment] 2018-01-04 06:27
@AngieCris , UI does not allow passing in CIDR, please see https://github.com/vmware/vic-ui/issues/287

**Comment by AngieCris** [comment] 2018-01-04 06:59
Confirmed via @lgayatri this is not a bug: the UI accepts CIDR and VCH deployment successfully goes thru.
We probably need to update the error message to something more informational, instead of giving the user a regular expression. I believe this is auto-generated by swagger @zjs Do you have an idea we can get around swagger generated error message?

**Comment by zjs** [comment] 2018-01-04 18:11
I don't see a way to influence the swagger-generated error message, but the UI could validate this field as well and provide a more friendly error earlier in the process.

**Comment by AngieCris** [comment] 2018-01-04 18:16
Closing this issue via #287 . UI should provide better warning/error messages for static IP field

**Closed by AngieCris** 2018-01-04 18:16 UTC
Labels: area/ui, kind/enhancement, team/lifecycle
