### ISSUE TITLE
Nightly test failures

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#421] opened 2018-03-22 20:33 UTC
We have been seeing failures consistently in nightly tests since our nimbus move and updates to the pieces of the UI. We need to investigate and fix the nightly tests prior to 1.4 release.

**Comment by lmalvins** [comment] 2018-03-28 15:58
Executed 27 of 27 specs SUCCESS in 1 min 39 secs.
[09:53:11] I/launcher - 0 instance(s) of WebDriver still running
[09:53:11] I/launcher - chrome #01 passed
[ Windows 10 - Chrome ] Create And Delete VCH On A Single Cluster ... | PASS |

**Comment by lmalvins** [comment] 2018-03-28 15:59
Executed 27 of 27 specs SUCCESS in 1 min 42 secs.
[09:55:30] I/launcher - 0 instance(s) of WebDriver still running
[09:55:30] I/launcher - firefox #01 passed
[ Windows 10 - Firefox ] Create And Delete VCH On A Single Cluster... | PASS |

**Comment by lmalvins** [comment] 2018-03-28 16:00
Executed 27 of 27 specs SUCCESS in 1 min 29 secs.
[10:00:21] I/launcher - 0 instance(s) of WebDriver still running
[10:00:21] I/launcher - chrome #01 passed
[ MacOS - Chrome ] Create And Delete VCH On A Single Cluster Envir... | PASS |

**Comment by lmalvins** [comment] 2018-03-28 16:01
Executed 27 of 27 specs SUCCESS in 1 min 52 secs.
[10:02:44] I/launcher - 0 instance(s) of WebDriver still running
[10:02:44] I/launcher - firefox #01 passed
[ MacOS - Firefox ] Create And Delete VCH On A Single Cluster Envi... | PASS |

**Comment by lmalvins** [comment] 2018-03-28 16:19
Executed 27 of 27 specs SUCCESS in 1 min 32 secs.
[10:04:51] I/launcher - 0 instance(s) of WebDriver still running
[10:04:51] I/launcher - chrome #01 passed
[ Windows 10 - Chrome ] Create And Delete VCH On A Multi-DC Enviro... | PASS |

**Comment by lmalvins** [comment] 2018-03-28 16:20
Executed 27 of 27 specs SUCCESS in 1 min 43 secs.
[10:07:11] I/launcher - 0 instance(s) of WebDriver still running
[10:07:11] I/launcher - firefox #01 passed
[ Windows 10 - Firefox ] Create And Delete VCH On A Multi-DC Envir... | PASS |

**Comment by javierfz1980** [comment] 2018-03-28 19:21
** 1-01-Basic-VCH-Create **
- Win and Mac (Chrome / FF) tests has been fixed with #422
- Win IE11 is still broken. The problem is on file 1-basic.e2e-spec.ts -> 'should redirect to VCH VM and display Create Wizard menu items' (line 198). The problem seems to be with the link to the recently created VCH. The link is found, but protractor can not click it on IE11, several workarounds has been teted with no success, this need more research.

** 1-02-Multi-DVS-VCH-Create **
- (Possible reason) This tests could be failing because at some point of the creation wizard is looking for networks 'net1' and 'net2' and they doesn't exists on VC. This could be related with the infrastructure step of the test.

**Closed** 2018-04-11 14:37 UTC
Labels: area/ui, component/test, priority/p1, team/lifecycle, triage/proposed-1.4
