### ISSUE TITLE
H5C keeps spinning with "Could not find any VIC appliance VM"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#222] opened 2017-12-12 07:47 UTC
Build: vic_v1.3.0-rc3.tar.gz

![image](https://user-images.githubusercontent.com/25006749/33872862-a528f53a-df3e-11e7-96f4-5af04bd8a17a.png)

Page keeps spinning with this error. I reloaded the page many times.

**Comment by lgayatri** [comment] 2017-12-12 08:02
@mdubya66 @mlh78750 
[dataservice.zip](https://github.com/vmware/vic-ui/files/1550697/dataservice.zip)

dataservice log is complaining of slow execution
```
[2017-12-12T07:58:09.388Z] [WARN ] http-bio-5090-exec-502       70017565 100378 200018 ProfilingUtil [queryId: q-20647:dataService.ts:getProperties:name:urn:vic:vic:Root:vic%252Fvic-root] The Data Service detected slow execution:
The query batch execution took too long: 19376 milliseconds.

A DataProviderAdapter ([Adapter: com.vmware.vic.VicUIDataAdapter@7668f2ea,  typeInfo: [vic:Root, [*], vic:VirtualContainerHostVm, [*], vic:ContainerVm, [*], vic:VmQueryResult, [*]]]) execution took too long: 19375 milliseconds.
Invocation id: q-20647:dataService.ts:getProperties:name:urn:vic:vic:Root:vic%252Fvic-root:VicUIDataAdapter:77704
Query names: [q-20647:dataService.ts:getProperties:name:urn:vic:vic:Root:vic%252Fvic-root]

The queries in the batch sent to the Data Service are:
Query[0]:

QuerySpec
 QueryName: q-20647:dataService.ts:getProperties:name:urn:vic:vic:Root:vic%252Fvic-root
 ResourceSpec
  Constraint: ObjectIdentityConstraint
   TargetType: null
   Target: urn:vic:vic:Root:vic/vic-root
  PropertySpec[1]
   ProviderType: vic:Root
   Relationship: null
   Properties[3]
    PropertyName: name
    PropertyName: primaryIconId
    PropertyName: labelIds
 ResultSpec:
  Offset: null
  MaxResultCount: null
  OrderingCriteria
   OrderPropertySpec[1]
    ProviderType: Object
    Relationship: null
    SortType: ASCENDING
    OrderingProperties[1]
     PropertyName: id
  Facets: null
 Options:
  VISE_TO_RISE_TRANSLATOR_STRICT_MODE=true
```

**Comment by jak-atx** [comment] 2017-12-12 20:00
looks similar to #228

**Comment by AngieCris** [comment] 2017-12-12 20:28
If it helps investigating the root cause: it happens to me when my VC auth session expires (does it automatically expire when the VC H5 client sits for too long?). I navigated back to the plugin page and the VCH inventory list begins spinning
http err code from console tab is 500

**Comment by jak-atx** [comment] 2017-12-12 22:02
@lgayatri can you check if this is related to session timeout? or are you able to reproduce this consistently upon login?

**Comment by lgayatri** [comment] 2017-12-13 04:13
I am hitting below issue consistently.
https://github.com/vmware/vic-ui/issues/206 VIC's H5C UI plugin fails to connect to endpoint 
![image](https://user-images.githubusercontent.com/25006749/33921454-df7a8a9a-dfe9-11e7-990d-2663d422564a.png)

**Comment by lgayatri** [comment] 2017-12-13 17:09
@jooskim , the reported issue seems to be wrt keep alive session . If I relogin or opens a new browser session, I dont see this issue.
@jak-atx

**Comment by jak-atx** [comment] 2017-12-13 17:24
Thanks for verifying @lgayatri 

Closing as dupe of #228, will address there.

**Closed by jak-atx** 2017-12-13 17:24 UTC
