### ISSUE TITLE
VCH Wizard hangs on Network section

### ISSUE THREAD

**Issue by emeirell** [vmware/vic-ui#504] opened 2018-05-28 13:20 UTC
I recently upgrade my VIC environment to version 1.4, including vSphere plugin.
When trying to create a new VCH the wizard hangs on the Network section with an endless spinning.

VIC: 1.4.0.1149
vCenter Appliance: 6.5.0.5300
Browser: Chrome 61.0.3163.100

The environment has 2 cluster, management and workload, both of them are using vSphere Distributed switches with Port Groups and Logical Switches.

<img width="1021" alt="vic" src="https://user-images.githubusercontent.com/22505995/40616144-45c2e812-6260-11e8-8be9-534d80576ac0.png">

Got the followin error fro Chrome Dev Tools:
VM4731 1.bc50ae8091d8d0c74ed0.chunk.js:1 TypeError: Cannot read property 'dvsHosts' of null
    at VM4714 0.02e8893b931a1b42c4d5.chunk.js:1
    at Array.map (<anonymous>)
    at e.project (VM4714 0.02e8893b931a1b42c4d5.chunk.js:1)
    at e._next (VM4704 main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e.E9/g.e.next (VM4704 main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e.checkIterators (VM4704 main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e.notifyNext (VM4704 main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e._next (VM4704 main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e.E9/g.e.next (VM4704 main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e._next (VM4704 main.1d9fb411ca52796f3c7e.bundle.js:1)

**Comment by Andy-Knight** [comment] 2018-05-29 11:55
Yep, i pulled 1.4.0 from the VMware official download page an hour ago and have the same thing when deploying a VCH through the wizard.
VIC: 1.4.0.1109
vCenter Appliance: 6.5.0.5300
Browser: Firefox 60.0.1
Client OS: Mac Sierra 10.12.6

**Comment by javierfz1980** [comment] 2018-05-29 20:12
This seems to be a known issue...

@pdaigle has found the same issue on his environment last week. Patrick's words, and same log (from viclifecylce channel):

"Hitting a bug with vic-ui in my lab. It starts up fine but when I get to the “Configure Networks” step, it just hangs (blue spinning wheel)." 

"TypeError: Cannot read property 'dvsHosts' of null
    at 0.02e8893b931a1b42c4d5.chunk.js:1
    at Array.map (<anonymous>)
    at e.project (0.02e8893b931a1b42c4d5.chunk.js:1)
    at e._next (main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e.next (main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e.checkIterators (main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e.notifyNext (main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e._next (main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e.next (main.1d9fb411ca52796f3c7e.bundle.js:1)
    at e._next (main.1d9fb411ca52796f3c7e.bundle.js:1)
(anonymous) @ 1.bc50ae8091d8d0c74ed0.chunk.js:1"

As a workaround he mentioned that Upgrading to 6.5.0.20000 seems to fix the issue.

We will have to figure out what is wrong anyway… I’ll take a look as soon as I can.

**Comment by javierfz1980** [comment] 2018-05-29 20:14
Please provide VC and ESXs build numbers...

Do we have a working environment were I can reproduce the error ?

Thanks.

**Comment by Andy-Knight** [comment] 2018-05-31 10:05
I updated my vCenter to 6.5.0.5700 Build 7119070 (6.5.0f) and left my hosts at 6.0.0, build 3620759 (my hosts aren't supported for 6.5).  Still the same issue.

**Comment by javierfz1980** [comment] 2018-05-31 13:48
Thanks for the info Andy, I’ll take a look with those vc builds and I’ll let you know my findings.

**Comment by zjs** [comment] 2018-06-12 23:51
@jak-atx:

How can I map the URIs from https://github.com/vmware/vic-ui/issues/504#issuecomment-393752095 to the corresponding vSphere API call?

Also, do we have any request/response logging for our outgoing API calls? Being able to explain how to reproduce this outside of VIC would be helpful when talking to other teams.

I'd like a crisp example of the behavior that changed between the vSphere versions to track down when that change was made (so we can clearly communicate to users when we will and won't see this issue) and what workarounds might exist.

**Comment by jak-atx** [comment] 2018-06-14 19:57
@javierfz1980 can you please list the corresponding network call(s)? I don't believe we are logging these anywhere currently.

**Comment by javierfz1980** [comment] 2018-06-14 20:18
Guys, sadly we are not logging anything... the specific network call is made here:

https://github.com/vmware/vic-ui/blob/a4f1012d0798bfca8223363eb574d54552f8515f/h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts#L297

And the call is made in the context of a call to the following service method:

https://github.com/vmware/vic-ui/blob/a4f1012d0798bfca8223363eb574d54552f8515f/h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts#L282

**Comment by renmaosheng** [comment] 2018-06-15 10:25
https://github.com/vmware/vic-ui/blob/a4f1012d0798bfca8223363eb574d54552f8515f/h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts#L305
Sometimes, the VDS query API returns null value for field of dvsHostsData['dvs:dvsHostsData'],
in that situation, it will throw Type Error if you try to fetch the inner field of dvsHostsData['dvs:dvsHostsData']['dvsHosts'];

we need add null value check logic in line 305:
e.g:
if(dvsHostsData['dvs:dvsHostsData'] !=null) {
     dvsHostsData['dvs:dvsHostsData']['dvsHosts'];
} else {
....
}
if some dvs doesn't have ESXi hosts connected to, the value of "dvsHostsData['dvs:dvsHostsData']" will be NULL for some VC version, the value can also be {dvsHosts[]}. That's why we observed differently due to VC version.

**Comment by renmaosheng** [comment] 2018-06-15 10:32
<img width="1594" alt="2018-06-15 6 29 24" src="https://user-images.githubusercontent.com/14900967/41463754-2e0b29c8-70ca-11e8-9c61-c97c151f7935.png">

**Comment by javierfz1980** [comment] 2018-06-15 12:03
@renmaosheng 
the null check it's ok to prevent the console to popup the error but it won't fix the  real issue, the wizard will still hang on the network step since if portgroups are not retrieved you can't select them and you can't proceed to the next step of the wizard.

The real issue is not the null or {} return, we can handle that... the real issue is that the endopint is returning null or {} when it should return the portgroups list.

**Comment by renmaosheng** [comment] 2018-06-15 12:12
if it is null, that means there is no ESXi hosts connected to that switch, we can't even put the vch VM on the portgroup of that switch as there is no compute resources, we should filter out the portgroup in UI, not shown them.

**Comment by javierfz1980** [comment] 2018-06-15 12:22
I know tha null or {} means there are no hosts connected to the vds, and that is the problem... because we know that there are host connected to that vds. the response shouldn’t be null or {}. It should be the list of host.

**Comment by zjs** [comment] 2018-06-15 23:32
Thanks, @javierfz1980. To investigate possible changes between the underlying infrastructure versions, it would be helpful to track down what is happening within the `/ui/data/properties/` call. (That appears to be something we've implemented: https://github.com/vmware/vic-ui/blob/e8e3267cacb84b3e60770c43dbe0dc0dfc04341c/h5c/vic-service/src/main/java/com/vmware/vic/mvc/DataAccessController.java)

**Comment by javierfz1980** [comment] 2018-06-16 01:50
@zjs thanks for your answer !
I'm not an expert on the vic-service, but as AFAIK, the endpoint that you are pointing is not handling the failing vds host request...

@jak-atx please correct me if I'm wrong, but our vic-service pointed by @zjs in the previous comment is handling requests made at `/ui/vic/rest/data/properties`
https://github.com/vmware/vic-ui/blob/e8e3267cacb84b3e60770c43dbe0dc0dfc04341c/h5c/vic-service/src/main/java/com/vmware/vic/mvc/DataAccessController.java#L77-L112

The failing vds hosts request (mentioned by me on the previous comments/screenshots) is trying to fetch data from `/ui/data/properties` and AFAIK this is a vcenter endpoint and is not under our scope (again I'm not an expert on the vic-service, so correct me if I'm wrong).

**Comment by zjs** [comment] 2018-06-18 16:13
> The failing vds hosts request (mentioned by me on the previous comments/screenshots) is trying to fetch data from `/ui/data/properties` and AFAIK this is a vcenter endpoint and is not under our scope (again I'm not an expert on the vic-service, so correct me if I'm wrong).

Is this the only place we do this, or is this a common pattern within our UI code? I think we need to update any code that's calling `/ui/data/properties` to call `/ui/vic/rest/data/properties` or something else we've implemented in our service layer..

**Closed** 2018-06-21 14:53 UTC
Labels: area/ui, priority/p0, status/needs-estimation, status/needs-triage, team/lifecycle
