### ISSUE TITLE
1.3 VIC UI plugin is not able to talk to latest VCSA 6.7

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#362] opened 2018-02-13 16:04 UTC
@jooskim 
Setup :
VCSA : 10.197.37.91 - administrator@vsphere.local/Admin!23

VIC OVA: vic-st-h2-198.eng.vmware.com - root/Admin!23

Regression Yes, as the same worked on 6.7 RC build.
```
[2018-02-12T11:09:01.366Z] [ERROR] http-nio-5090-exec-5          org.springframework.web.servlet.DispatcherServlet                 Context initialization failed org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from ServletContext resource [/WEB-INF/spring/bundle-context.xml]; nested exception is org.springframework.beans.FatalBeanException: NamespaceHandler class [org.springframework.web.servlet.config.MvcNamespaceHandler] for namespace [http://www.springframework.org/schema/mvc] not found; nested exception is java.lang.ClassNotFoundException: org.springframework.web.servlet.config.MvcNamespaceHandler not found from bundle [com.vmware.vic-1.3.1.687-com.vmware.vic.ui]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:414)
  
```

Will upload the upgrade log asap.

**Comment by lgayatri** [comment] 2018-02-13 16:15
![image](https://user-images.githubusercontent.com/25006749/36160036-387dd28a-1106-11e8-8c1f-5ded921a1c39.png)
[vic-ui.log](https://github.com/vmware/vic-ui/files/1720654/vic-ui.log)
Here are the screen shot and log.

**Comment by jooskim** [comment] 2018-02-13 21:09
Could you attach the original buzilla ticket number?

**Comment by lgayatri** [comment] 2018-02-14 05:04
Here : 2057028

**Comment by jooskim** [comment] 2018-02-14 15:55
Based on Aleksandar's comments from the ticket, trying to add missing packages to the MANIFEST.MF file would lead to other issues, the first of which is documented in bullet point 5 at https://confluence.eng.vmware.com/pages/viewpage.action?pageId=218806049. The solution for the issue is marked as incompatible with the vSphere 6.5 line once applied, but fortunately there is a workaround to make the plugin backwards compatible with 6.5.

Action items:
1. Deploy VCVA 6.7 ob-7797199
2. Upgrade vSphere Client SDK to the corresponding build
3. Start the new dev environment and import the plugin
4. Confirm the same errors

**Comment by lgayatri** [comment] 2018-02-14 17:18
@jooskim , please free to use my VCSA which is on 7797199

**Comment by jooskim** [comment] 2018-02-14 17:20
Ok. I'll get back to this once it's prioritized.

**Closed** 2018-02-20 21:49 UTC
Labels: area/ui, kind/bug, priority/p1, status/needs-estimation, team/lifecycle
