### ISSUE TITLE
Version number mismatch between OVA and vic-ui

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#269] opened 2018-01-02 05:40 UTC
This issue was seen is RC3 as well(verified from older screenshots I pasted in issues)
Build: https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.3.0-rc5-2996-f8cc7317.ova 

vic-ui shows the version as rc6
![image](https://user-images.githubusercontent.com/25006749/34475043-750de73c-efad-11e7-83dd-059f22546c37.png)

This mismatch will be confusing.

**Comment by lgayatri** [comment] 2018-01-02 05:40
@mdubya66 @jooskim

**Comment by jooskim** [comment] 2018-01-02 18:03
It used to be the VIC engine version a while ago, but we changed it to show only the UI version in this specific page because it would make it easier for us to track down UI issues if any happens. @jak-atx What do you think about displaying the version in the format like `v1.3.0-rc6.505 (Engine: v1.3.0-rc5.xxxxx)`?

**Comment by jooskim** [comment] 2018-01-02 18:07
Not sure if this is a high priority. @AngieCris any reason for marking it high?

**Comment by mdubya66** [comment] 2018-01-02 23:36
This is not a bug, versions can and will diverge during development.

**Comment by jak-atx** [comment] 2018-01-22 22:36
Closing as non-issue.

**Closed by jak-atx** 2018-01-22 22:36 UTC
Labels: area/ui, team/lifecycle
