### ISSUE TITLE
VCH inventory list and create wizard fails to load when VC auth session expires

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic-ui#228] opened 2017-12-12 19:54 UTC
When the VC H5 client sits for too long and the session expires, VCH inventory list fails to load/reload with a 500 internal server error in console output. After I log out and re-login, VCH inventory list loads successfully with no errors. 
In this case, it would be more helpful to the user if we can display some friendly error/warning message reminding them that the VC session is expired (if it's detectable). 
Screenshot:

![screen shot 2017-12-12 at 1 49 13 pm](https://user-images.githubusercontent.com/6562128/33905232-909cef86-df43-11e7-9114-7934c1ad2698.png)

**Comment by jak-atx** [comment] 2017-12-12 19:58
seems to be related to (or same issue as) #222

**Comment by AngieCris** [comment] 2017-12-12 20:11
Yes it looks like a duplicate of #222 @jak-atx

**Comment by jak-atx** [comment] 2017-12-12 22:03
Not 100% certain they are the same yet. Requesting @lgayatri to verify if #222 is fixed by session refresh. If so, we can close this one as dupe.

**Comment by AngieCris** [comment] 2017-12-13 16:31
According to @lgayatri it seems like she's consistently hitting this error. 
In my case, it only happens when I let the VC H5 client sit silent for too long, to a point when maybe the browser session or VC auth session expires. Then when I go back to the VCH inventory list, it hangs, failing to load the list.

**Comment by jooskim** [comment] 2017-12-14 14:43
H5 Client seems to have a way to check if the session has expired, which unfortunately isn't obvious  for a plugin running on it. Another way to tackle this issue would be to catch the 500 error in the Angular service, for which I need to first reproduce the session timeout in H5 Client before I can gauge where to make improvements.

**Comment by AngieCris** [comment] 2017-12-15 21:18
this is seen too:
![image](https://user-images.githubusercontent.com/6562128/34060874-43214f62-e1ab-11e7-9287-341b86174584.png)

**Comment by jooskim** [comment] 2017-12-28 19:08
I took a look at this issue in another angle and found out some meaningful information:

1. There is an endpoint in H5 Client that returns the session information for the current user: `https://$VCIP/ui/usersession` which will normally return a 200 response if the session is valid, otherwise it will return a 401.
2. The session can be forcefully invalidated by deleting a cookie named JSESSIONID for path `/ui/`.

**Comment by AngieCris** [comment] 2018-01-05 16:42
As reported by @lgayatri 

![image](https://user-images.githubusercontent.com/6562128/34618616-ead8d6c6-f204-11e7-95ea-d8fd44b1eeda.png)

At the very last step of create wizard, H5 session expired before the HTTP request got sent. Then after hitting create button, the create failed with generic error message.

**Comment by jak-atx** [comment] 2018-01-22 21:06
This issue also seems to be causing the behavior seen here: https://github.com/vmware/vic-ui/issues/163

**Comment by AngieCris** [comment] 2018-02-12 18:57
@stuclem Do we have sth like a `known-issue` section in our documentation?
Today (02/12) in GSS someone mentioned this issue and they're not aware that we have a ticket open for it. Do you think if it's a good idea for us to put it in the doc or sth?

**Comment by mdubya66** [comment] 2018-02-13 01:16
added kind/note

**Comment by AngieCris** [comment] 2018-02-13 23:03
@jak-atx @jooskim Do we want this to go into next sprint since it's a P1 bug and it's mentioned in GSS?

**Comment by stuclem** [comment] 2018-02-23 15:01
@AngieCris apologies for noticing this one sooner. Here's an attempt at a release note:

- <b>VCH inventory list and create wizard fails to load when vCenter Server session expires. [#228](https://github.com/vmware/vic-ui/issues/228)</b><br>If the vCenter Server authentication sessions expires, attempts to reload the VCH inventory list or to use the Create VCH wizard fail with a 500 internal server error.

   Workaround:  Log out of vSphere Client and log in again.

Does that cover it?

**Comment by AngieCris** [comment] 2018-02-23 17:58
@stuclem Thanks. I'm not sure if the `500 internal server error` would confuse the user (they can't see the status code unless they inspect the page), maybe we could say something along the lines of `If the vCenter server authentication session expires, reloading VCH inventory list would hang with an error message of: "Could not find any VIC appliance VM", and attempt of creating a VCH could fail with error message "Error creating VCH". When this happens, please reload the browser session and re-authenticate to vCenter.` Does this look okay to you?

**Comment by stuclem** [comment] 2018-02-26 09:52
Thanks @AngieCris. I updated the [RN entry](https://github.com/vmware/vic-ui/releases/tag/v1.3.1#knownissues) accordingly.

**Closed** 2018-03-06 19:40 UTC
Labels: area/ui, kind/bug, priority/p1, team/lifecycle
