### ISSUE TITLE
vic-machine output truncated in h5 client

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic-ui#236] opened 2017-12-13 18:58 UTC
Output should conclude with output of the certificates' location, output of the docker command to access the VCH, and a success message. Instead it is truncated shortly after certificate generation:

![truncated](https://user-images.githubusercontent.com/3743903/33956532-6dcedcbe-e004-11e7-9ee1-ab04661ef206.gif)

**Comment by AngieCris** [comment] 2017-12-13 19:03
@gigawhitlocks Do you mean this part of creation log that is normally included in CLI create:
```
Dec  6 2017 23:14:27.626-06:00 DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Dec  6 2017 23:14:35.501-06:00 DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [7.87647035s] 
Dec  6 2017 23:14:48.063-06:00 DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [20.437498504s] 
Dec  6 2017 23:14:48.063-06:00 DEBUG [ END ] op=5134.1 [vic/lib/install/management.(*Dispatcher).uploadImages:115] [20.439434078s] 
Dec  6 2017 23:14:48.063-06:00 DEBUG [BEGIN] op=5134.1 [vic/lib/install/management.(*Dispatcher).startAppliance:100]
Dec  6 2017 23:14:49.987-06:00 DEBUG [ END ] op=5134.1 [vic/lib/install/management.(*Dispatcher).startAppliance:100] [1.924203476s] 
Dec  6 2017 23:14:49.987-06:00 DEBUG [ END ] op=5134.1 [vic/lib/install/management.(*Dispatcher).CreateVCH:42] [37.137298369s] VCH-0-6705
Dec  6 2017 23:14:49.988-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).ensureApplianceInitializes:1066]
Dec  6 2017 23:14:49.988-06:00 INFO  op=5134.1: Waiting for IP information
Dec  6 2017 23:14:49.988-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] guestinfo.vice..init.networks|client.assigned.IP
Dec  6 2017 23:15:11.306-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] [21.317937891s] guestinfo.vice..init.networks|client.assigned.IP
Dec  6 2017 23:15:11.306-06:00 INFO  op=5134.1: Waiting for major appliance components to launch
Dec  6 2017 23:15:11.306-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] guestinfo.vice..init.sessions|vicadmin.started
Dec  6 2017 23:15:11.513-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] [207.469003ms] guestinfo.vice..init.sessions|vicadmin.started
Dec  6 2017 23:15:11.513-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] guestinfo.vice..init.sessions|docker-personality.started
Dec  6 2017 23:15:11.728-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] [215.032498ms] guestinfo.vice..init.sessions|docker-personality.started
Dec  6 2017 23:15:11.729-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] guestinfo.vice..init.sessions|port-layer.started
Dec  6 2017 23:15:21.372-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] [9.643495881s] guestinfo.vice..init.sessions|port-layer.started
Dec  6 2017 23:15:21.372-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).applianceConfiguration:755]
Dec  6 2017 23:15:21.372-06:00 DEBUG [BEGIN] op=5134.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:519] VM(VirtualMachine:vm-59) Properties([config.extraConfig])
Dec  6 2017 23:15:21.372-06:00 DEBUG op=5134.1: properties: [config.extraConfig summary.runtime.connectionState]
Dec  6 2017 23:15:21.433-06:00 DEBUG [ END ] op=5134.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:519] [60.496528ms] VM(VirtualMachine:vm-59) Properties([config.extraConfig])
Dec  6 2017 23:15:21.436-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).applianceConfiguration:755] [63.600786ms] 
Dec  6 2017 23:15:21.436-06:00 DEBUG op=5134.1:   State of components:
Dec  6 2017 23:15:21.436-06:00 DEBUG op=5134.1:     "docker-personality": "started successfully"
Dec  6 2017 23:15:21.436-06:00 DEBUG op=5134.1:     "port-layer": "started successfully"
Dec  6 2017 23:15:21.436-06:00 DEBUG op=5134.1:     "vicadmin": "started successfully"
Dec  6 2017 23:15:21.436-06:00 INFO  op=5134.1: Obtained IP address for client interface: "10.160.135.89"
Dec  6 2017 23:15:21.437-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).ensureApplianceInitializes:1066] [31.449008062s] 
Dec  6 2017 23:15:21.437-06:00 INFO  op=5134.1: Checking VCH connectivity with vSphere target
Dec  6 2017 23:15:22.951-06:00 INFO  op=5134.1: vSphere API Test: https://10.160.129.205 vSphere API target responds as expected
Dec  6 2017 23:15:22.952-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).CheckDockerAPI:835]
Dec  6 2017 23:15:22.952-06:00 DEBUG op=5134.1: Loading CAs for client auth
Dec  6 2017 23:15:22.982-06:00 DEBUG [BEGIN]  [vic/pkg/certificate.ParseCertificate:258]
Dec  6 2017 23:15:22.982-06:00 DEBUG [ END ]  [vic/pkg/certificate.ParseCertificate:258] [270.271µs] 
Dec  6 2017 23:15:23.099-06:00 DEBUG op=5134.1: Matched "sc-rdops-vm05-dhcp-135-89.eng.vmware.com." for use against host certificate
Dec  6 2017 23:15:23.099-06:00 DEBUG op=5134.1: Host address set to: "sc-rdops-vm05-dhcp-135-89.eng.vmware.com"
Dec  6 2017 23:15:23.100-06:00 DEBUG op=5134.1: Assigning certificates for client auth
Dec  6 2017 23:15:23.100-06:00 DEBUG op=5134.1: Docker API endpoint: https://sc-rdops-vm05-dhcp-135-89.eng.vmware.com:2376/info
Dec  6 2017 23:15:24.214-06:00 DEBUG op=5134.1: connection refused
Dec  6 2017 23:15:24.215-06:00 DEBUG op=5134.1: Components not yet initialized, retrying
Dec  6 2017 23:15:24.309-06:00 DEBUG op=5134.1: connection refused
Dec  6 2017 23:15:25.100-06:00 DEBUG op=5134.1: Components not yet initialized, retrying
Dec  6 2017 23:15:25.190-06:00 DEBUG op=5134.1: connection refused
Dec  6 2017 23:15:26.100-06:00 DEBUG op=5134.1: Components not yet initialized, retrying
Dec  6 2017 23:15:26.190-06:00 DEBUG op=5134.1: connection refused
Dec  6 2017 23:15:27.100-06:00 DEBUG op=5134.1: Components not yet initialized, retrying
Dec  6 2017 23:15:27.189-06:00 DEBUG op=5134.1: connection refused
Dec  6 2017 23:15:28.100-06:00 DEBUG op=5134.1: Components not yet initialized, retrying
Dec  6 2017 23:15:30.024-06:00 DEBUG op=5134.1: Portlayer has established volume stores (default)
Dec  6 2017 23:15:30.025-06:00 DEBUG op=5134.1: Confirmed port layer is operational
Dec  6 2017 23:15:30.025-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).CheckDockerAPI:835] [7.073086524s] 
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: Initialization of appliance successful
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: 
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: VCH Admin Portal:
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: https://sc-rdops-vm05-dhcp-135-89.eng.vmware.com:2378
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: 
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: Published ports can be reached at:
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: 10.160.135.89
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: 
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: Docker environment variables:
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/home/vicadmin/vic/VCH-0-6705 DOCKER_HOST=sc-rdops-vm05-dhcp-135-89.eng.vmware.com:2376
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: 
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: Environment saved in VCH-0-6705/VCH-0-6705.env
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: 
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: Connect to docker:
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: docker -H sc-rdops-vm05-dhcp-135-89.eng.vmware.com:2376 --tlsverify --tlscacert="VCH-0-6705/ca.pem" --tlscert="VCH-0-6705/cert.pem" --tlskey="VCH-0-6705/key.pem" info
Dec  6 2017 23:15:30.025-06:00 INFO  op=5134.1: Installer completed successfully
```

**Comment by gigawhitlocks** [comment] 2017-12-13 19:20
Yes, that's what I was referring to. I searched and could not find an open issue. (looks like I was looking in the wrong repo, as I assumed it was a UI issue)

**Comment by gigawhitlocks** [comment] 2017-12-13 19:21
The log doesn't tell them the location and neither the log, the UI, nor Admiral, tells them that they even need the certificates. They will have to first become frustrated at the Add VCH screen in Admiral and then refer to the documentation, where hopefully they will find what they need.

**Comment by zjs** [comment] 2017-12-13 20:29
Closing as a duplicate of vmware/vic#6924.

**Closed by zjs** 2017-12-13 20:29 UTC
Labels: team/lifecycle
