### ISSUE TITLE
VIC's H5C UI plugin fails to connect to endpoint

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#206] opened 2017-12-08 11:41 UTC
@jooskim @mdubya66 

VIC RC3 : vic-v1.3.0-rc3-2784-7d227d5c.ova

![image](https://user-images.githubusercontent.com/25006749/33764346-13ed64e0-dc3a-11e7-80f8-f8eff21d3510.png)

Endpoint is OK from Browser:
![image](https://user-images.githubusercontent.com/25006749/33764410-46846d90-dc3a-11e7-85f0-1b872e0d6699.png)

VCSA: wdc-stvc3944-146-dhcp15.eng.vmware.com
administrator@vsphere.local/Admin!23
root/Admin!23

Please access the setup directly.

**Comment by lgayatri** [comment] 2017-12-08 12:11
This issue seems to be intermittent, when I tried after multiple refresh - it worked but I hit https://github.com/vmware/vic-ui/issues/208

**Comment by jak-atx** [comment] 2017-12-08 16:49
Tried with your setup but was not able to reproduce. I think we need a better way of directing the user to open this, accept certificate, and then navigate back and refreshing. It doesn't seem completely obvious that these are the steps necessary.

**Comment by jooskim** [comment] 2017-12-09 00:45
At some point I thought might've hit this issue - https://github.com/vmware/vic-ui/issues/195 which is resolved in VIC-UI RC4. But that you hit that other issue seems to indicate there's another issue.

**Comment by jooskim** [comment] 2017-12-14 14:55
@lgayatri Please see my latest comment check if you have a cookie named XSRF_TOKEN in your browser cookies list. If you do, delete it and try refreshing. Again, this issue is resolved in vic-ui rc4.

**Comment by jooskim** [comment] 2017-12-29 19:06
Need to confirm with @lgayatri if the issue is resolved in RC4+.

**Comment by lgayatri** [comment] 2018-01-02 05:37
Blocked all Cookies in the browser and refreshed the browser after which I could not see this issue. 

Verified on RC5, https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.3.0-rc5-2996-f8cc7317.ova

![image](https://user-images.githubusercontent.com/25006749/34475005-1f8a58cc-efad-11e7-823b-abf3b76ce585.png)


VCSA: wdc-stvc3944-146-dhcp15.eng.vmware.com
administrator@vsphere.local/Admin!23
root/Admin!23

Please access the setup directly.

**Comment by jooskim** [comment] 2018-01-02 18:35
You don't have to block cookies to get around the issue. Beginning from RC5 you will not see the issue whether or not your browser contains the `XSRF_TOKEN` cookie. Closing the issue

**Closed by jooskim** 2018-01-02 18:35 UTC
Labels: area/ui, kind/bug, status/need-info, team/lifecycle
