### ISSUE TITLE
1.3 ui upgrade warns about an older version

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-ui#183] opened 2017-12-05 20:19 UTC
root@vcsa-01a [ ~/vic/ui/VCSA ]# ./upgrade.sh
-------------------------------------------------------------
This script will upgrade vSphere Integrated Containers plugin
for vSphere Client (HTML) and vSphere Web Client (Flex).

Please provide connection information to the vCenter Server.
-------------------------------------------------------------
Enter FQDN or IP to target vCenter Server: vcsa-01a.corp.local
Enter your vCenter Administrator Username: administrator@corp.local
Enter your vCenter Administrator Password:

SHA-1 key fingerprint of host 'vcsa-01a.corp.local' is 'F7:68:F0:93:F4:EC:B7:FE:C1:02:3F:F3:AB:62:1A:50:E8:9A:0E:85'
Are you sure you trust the authenticity of this host (yes/no)? yes

-------------------------------------------------------------
Checking existing plugins...
-------------------------------------------------------------
Plugin with key 'com.vmware.vic' is already registered with VC. (Version: 1.2.1.13858)
Plugin with key 'com.vmware.vic.ui' is already registered with VC (Version: 1.2.1.13858)
The version you are about to install is '1.3.0.406'.

You are trying to install plugins of an older or same version. For changes to take effect,
please restart the vSphere Web Client and vSphere Client services after upgrade is completed
For instructions, please refer to https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/ts_ui_not_appearing.html

Are you sure you want to continue (yes/no)? yes

-------------------------------------------------------------
Preparing to upgrade vCenter Extension vSphere Integrated Containers-FlexClient...
-------------------------------------------------------------
Dec  5 2017 20:14:43.904Z INFO  ### Installing UI Plugin ####
Dec  5 2017 20:14:44.227Z INFO  Removing existing plugin to force install
Dec  5 2017 20:14:56.385Z INFO  Removed existing plugin
Dec  5 2017 20:14:56.385Z INFO  Installing plugin
Dec  5 2017 20:15:03.164Z INFO  Installed UI plugin

-------------------------------------------------------------
Preparing to upgrade vCenter Extension vSphere Integrated Containers-H5Client...
-------------------------------------------------------------
Dec  5 2017 20:15:03.332Z INFO  ### Installing UI Plugin ####
Dec  5 2017 20:15:03.725Z INFO  Removing existing plugin to force install
Dec  5 2017 20:15:10.049Z INFO  Removed existing plugin
Dec  5 2017 20:15:10.050Z INFO  Installing plugin
Dec  5 2017 20:15:16.258Z INFO  Installed UI plugin
Dec  5 2017 20:15:17.902Z INFO  Found 1 VM(s) tagged as OVA
Dec  5 2017 20:15:17.913Z INFO  Attempting to configure ManagedByInfo
Dec  5 2017 20:15:19.301Z INFO  Successfully configured ManagedByInfo

--------------------------------------------------------------
VIC Engine UI upgrader exited successfully

**Comment by stuclem** [comment] 2018-01-10 15:53
Release note:

- <b>Plug-in upgrade script incorrectly warns that you are trying to install an older version. [#183](https://github.com/vmware/vic-ui/issues/183)</b><br>When you run the plug-in upgrade script, the output warns you that `You are trying to install plugins of an older or same version` even when you are installing a later version of the plug-in.  

   Workaround: Ignore the warning and enter `yes` to proceed with the upgrade.

@jooskim is this OK?

**Comment by jooskim** [comment] 2018-01-11 16:20
Short answer is yes.

To give you more context on this as a FYI, the script checks the build number portion between the existing version and the new version. In this case 13858 is larger than 406 so the script proceeded as if the user was attempting to install an older version, which actually isn't true.

**Comment by stuclem** [comment] 2018-01-11 16:40
Thanks @jooskim. I don't think that we need to mention the details, though.

**Comment by jak-atx** [comment] 2018-01-22 22:00
This was caused by a change from using VIC build number to VIC-UI build number. Users will see this issue when upgrading to 1.3.0 only. Subsequent upgrades will not see this issue since the install will then have a higher build number. Since we have noted this and there is no code change to be made here, closing this.

**Closed by jak-atx** 2018-01-22 22:00 UTC
Labels: area/ui, kind/bug, priority/medium, team/lifecycle

**Comment by stuclem** [comment] 2018-02-06 14:31
@jak-atx I assume that this issue still shows up for upgrades from 1.2.x to 1.3.1, but not for upgrades from 1.3.0 to 1.3.1. Leaving this as a known issue in the 1.3.1 release notes pending confirmation.
