### ISSUE TITLE
RC6 : CIDR format should be used when accepting Static IP for VCH

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#287] opened 2018-01-04 06:17 UTC
@jak-atx @jooskim @mdubya66 

Build : vic-v1.3.0-rc6-3010-f8cc7317.ova

root@Ubuntu-VIc:/home/vmlib/VIC/VIC-1.3/vic# ./vic-machine-linux --version
vic-machine-linux version v1.3.0-rc6-15551-473375a

root@Ubuntu-VIc:/home/vmlib/VIC/VIC-1.3/vic# ./vic-ui-linux --version
vic-ui-linux version 15551-473375a0a80f4f91ac445ecb616056fc5cfcbcc7

The below is the command generated by UI during VCH creation:

./vic-machine-linux create --name virtual-container-host --compute-resource /Datacenter/host/Cluster/w2-hs2-d2612.eng.vmware.com --image-store CPBU_2TB_01 --base-image-size 8GB --bridge-network vxw-dvs-3444-virtualwire-1-sid-5000-VCH-LS-1 --bridge-network-range 172.16.0.0/12 --public-network DPortGroup --public-network-ip 10.197.37.192 --public-network-gateway 10.197.37.253 --dns-server 10.142.7.21 --tls-cname virtual-container-host --organization virtual-container-host --certificate-key-size 2048 --no-tlsverify --user Administrator@VSPHERE.LOCAL --thumbprint C1:6D:3E:41:A5:89:5E:89:FB:DB:82:2F:32:82:8E:54:53:8B:65:34 --target wdc-stvc3944-146-dhcp15.eng.vmware.com/Datacenter --ops-user Administrator@vsphere.local
INFO[0000] ### Installing VCH ####
INFO[0000] vSphere password for Administrator@VSPHERE.LOCAL:
INFO[0003] vSphere password for Administrator@vsphere.local:
ERRO[0006] --------------------
ERRO[0006] vic-machine-linux create failed: Failed to parse the provided public network IP address 10.197.37.192: invalid CIDR address: 10.197.37.192

Either CLI should update the static IP address of VCH to use CIDR format or UI should enforce the user to pass CIDR format in the below screen: The hint should be updated.

![image](https://user-images.githubusercontent.com/25006749/34552788-a4ec3498-f149-11e7-941e-940b56ff73e8.png)

**Comment by lgayatri** [comment] 2018-01-04 06:52
The hint showed as IP address, hence I went ahead only to hit the issue. It should be updated to show that CIDR is required.

**Comment by AngieCris** [comment] 2018-01-04 07:03
Confirmed not a bug via @lgayatri . The CLI and UI expect CIDR format for static IP addresses, and VCH deployment succeeds with CIDR supplied. 

@jak-atx @jooskim Is it better if we show warning on the UI side saying `CIDR address is not valid` instead of `IP Address is not valid`? 
The user would expect the UI to accept IP address since the warning said so, and would get confused when the deployment didn't go thru. And the error message returned from API would contain a long confusing regex, making it worse
Ping Zach for advice @zjs

**Comment by zjs** [comment] 2018-01-04 18:10
It seems like UI-side validation of this field, with a friendly error message, would result in a much better user experience than the current API-side error.

**Comment by mdubya66** [comment] 2018-01-10 21:01
If we have a PR merged by Jan 17 then we can take this fix for 1.3.1

**Closed** 2018-01-16 15:58 UTC
Labels: area/ui, kind/enhancement, team/lifecycle, triage/proposed-1.3.1
