### ISSUE TITLE
VCH Wizard. The UI seems to hang after hitting the cancel button

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic-ui#163] opened 2017-12-01 19:25 UTC
**VIC version:**
vic-v1.3.0-rc2-2628-9e2a95b6.ova
**Deployment details:**
Nimbus deployment, no VCH
**Steps to reproduce:**
Run the Wizard 
**Actual behavior:**
I used the Wizard to create a VCH. I stopped on the Security page and let it sit there for 15 mins or so. Then I hit the Cancel button. The UI is stuck with a infinitely spinning circle. This may be caused by the fact that the VSphere credentials have expired.
**Expected behavior:**
The UI should either execute the Cancel command or go back to the Login screen.

**Comment by AngieCris** [comment] 2018-01-04 22:48
Might be a duplicate of https://github.com/vmware/vic-ui/issues/228
It could be that the H5 session expired

**Comment by jak-atx** [comment] 2018-01-22 21:05
Closing and marking as duplicate, will reference this issue in #228

**Closed by jak-atx** 2018-01-22 21:05 UTC
Labels: area/ui, team/lifecycle, triage/proposed-1.4
